version: "2"
services:
  product-review:
    build:
      context: ./product-review/
      dockerfile: Dockerfile
    image: product-review
    container_name: product-review
    ports:
      - "8081:8080"
  product-service:
    build:
      context: ./product-service/
      dockerfile: Dockerfile
    image: product-service
    container_name: product-service
    ports:
      - "8080:8080"
    environment:
      - REVIEW_API_ADDR=product-review:8081
